# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App2

 pod 'Alamofire', '~> 4.0'
    pod 'AlamofireImage', '~> 3.1'
    pod 'SwiftyJSON'
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
    pod 'ReachabilitySwift', '~> 3'
    pod 'SDWebImage', '~>3.8'
    
end
